### ISSUE TITLE
LN3 1.2 Duplicate Entries

### ISSUE THREAD

**Issue by orlandocosta76** [LDSSA/batch2-blu12#1]
After converting the matrix from COO to CSR it is said:
_The reduction from 500 to 460 stored element in the matrix is due to the consolidation.
We can confirm this by calling .max() on it._

Did not get the point of using max, in particular since calling  `max()` on both COO and CSR the output is the same, what am I missing?

**Comment by yani992** [comment]
I think that, if you find a number which is bigger than 1 it means that particular observation had more than one entry, i.e. it was a duplicate. If you count the number of values bigger than 1 after the consolidation `clicks_[clicks > 1].shape[1] + 1` , you should get the difference between 500 and 460.

**Comment by orlandocosta76** [comment]
@yani992 You're reasoning makes sense, but in that case `max` is not the right tool to check right?
