### ISSUE TITLE
Exercise Notebook 5

### ISSUE THREAD

**Issue by ruimgf** [LDSSA/batch2-blu12#4]
![image](https://user-images.githubusercontent.com/13384576/44542118-d419c800-a703-11e8-97c3-3c5dc203cae7.png)

I am getting this error on the assert, i didn't see the reason.

**Comment by orlandocosta76** [comment]
@ruimgf Are you using the Prediction object itself or it's `est `field? It should be the latter.

**Comment by ruimgf** [comment]
Yep, it is this. Thanks @orlandocosta76

**Comment by HugoDLopes** [comment]
@orlandocosta76 thanks a lot! This is very subtle
